apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: python-example
spec:
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: '1'
  flinkVersion: v1_20
  image: aliyanraf/flink-python-example:latest
  imagePullPolicy: Always
  job:
    args:
    - -pyclientexec
    - /usr/local/bin/python3
    - -py
    - /opt/flink/python_demo.py
    entryClass: org.apache.flink.client.python.PythonDriver
    jarURI: local:///opt/flink/lib/flink-sql-connector-kafka-1.17.2.jar
    parallelism: 6
    upgradeMode: stateless
  jobManager:
    resource:
      cpu: 1
      memory: 2048m
  mode: standalone
  serviceAccount: flink
  taskManager:
    resource:
      cpu: 1
      memory: 1024m
